/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransmissorasRouteImport } from './routes/transmissoras'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as InvestidoresRouteImport } from './routes/investidores'
import { Route as EticaRouteImport } from './routes/etica'
import { Route as EsgRouteImport } from './routes/esg'
import { Route as EolicasRouteImport } from './routes/eolicas'
import { Route as EmpresasRouteImport } from './routes/empresas'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InvestidoresIndexRouteImport } from './routes/investidores/index'
import { Route as InvestidoresTransmissoraSpmgSARouteImport } from './routes/investidores/transmissora-spmg-s-a'
import { Route as InvestidoresRelatoriosAgenteFiduciarioRouteImport } from './routes/investidores/relatorios-agente-fiduciario'
import { Route as InvestidoresOutrosDocumentosRouteImport } from './routes/investidores/outros-documentos'
import { Route as InvestidoresDemonstracoesFinanceirasRouteImport } from './routes/investidores/demonstracoes-financeiras'

const TransmissorasRoute = TransmissorasRouteImport.update({
  id: '/transmissoras',
  path: '/transmissoras',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestidoresRoute = InvestidoresRouteImport.update({
  id: '/investidores',
  path: '/investidores',
  getParentRoute: () => rootRouteImport,
} as any)
const EticaRoute = EticaRouteImport.update({
  id: '/etica',
  path: '/etica',
  getParentRoute: () => rootRouteImport,
} as any)
const EsgRoute = EsgRouteImport.update({
  id: '/esg',
  path: '/esg',
  getParentRoute: () => rootRouteImport,
} as any)
const EolicasRoute = EolicasRouteImport.update({
  id: '/eolicas',
  path: '/eolicas',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasRoute = EmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestidoresIndexRoute = InvestidoresIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InvestidoresRoute,
} as any)
const InvestidoresTransmissoraSpmgSARoute =
  InvestidoresTransmissoraSpmgSARouteImport.update({
    id: '/transmissora-spmg-s-a',
    path: '/transmissora-spmg-s-a',
    getParentRoute: () => InvestidoresRoute,
  } as any)
const InvestidoresRelatoriosAgenteFiduciarioRoute =
  InvestidoresRelatoriosAgenteFiduciarioRouteImport.update({
    id: '/relatorios-agente-fiduciario',
    path: '/relatorios-agente-fiduciario',
    getParentRoute: () => InvestidoresRoute,
  } as any)
const InvestidoresOutrosDocumentosRoute =
  InvestidoresOutrosDocumentosRouteImport.update({
    id: '/outros-documentos',
    path: '/outros-documentos',
    getParentRoute: () => InvestidoresRoute,
  } as any)
const InvestidoresDemonstracoesFinanceirasRoute =
  InvestidoresDemonstracoesFinanceirasRouteImport.update({
    id: '/demonstracoes-financeiras',
    path: '/demonstracoes-financeiras',
    getParentRoute: () => InvestidoresRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/empresas': typeof EmpresasRoute
  '/eolicas': typeof EolicasRoute
  '/esg': typeof EsgRoute
  '/etica': typeof EticaRoute
  '/investidores': typeof InvestidoresRouteWithChildren
  '/portfolio': typeof PortfolioRoute
  '/sobre': typeof SobreRoute
  '/transmissoras': typeof TransmissorasRoute
  '/investidores/demonstracoes-financeiras': typeof InvestidoresDemonstracoesFinanceirasRoute
  '/investidores/outros-documentos': typeof InvestidoresOutrosDocumentosRoute
  '/investidores/relatorios-agente-fiduciario': typeof InvestidoresRelatoriosAgenteFiduciarioRoute
  '/investidores/transmissora-spmg-s-a': typeof InvestidoresTransmissoraSpmgSARoute
  '/investidores/': typeof InvestidoresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/empresas': typeof EmpresasRoute
  '/eolicas': typeof EolicasRoute
  '/esg': typeof EsgRoute
  '/etica': typeof EticaRoute
  '/portfolio': typeof PortfolioRoute
  '/sobre': typeof SobreRoute
  '/transmissoras': typeof TransmissorasRoute
  '/investidores/demonstracoes-financeiras': typeof InvestidoresDemonstracoesFinanceirasRoute
  '/investidores/outros-documentos': typeof InvestidoresOutrosDocumentosRoute
  '/investidores/relatorios-agente-fiduciario': typeof InvestidoresRelatoriosAgenteFiduciarioRoute
  '/investidores/transmissora-spmg-s-a': typeof InvestidoresTransmissoraSpmgSARoute
  '/investidores': typeof InvestidoresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/empresas': typeof EmpresasRoute
  '/eolicas': typeof EolicasRoute
  '/esg': typeof EsgRoute
  '/etica': typeof EticaRoute
  '/investidores': typeof InvestidoresRouteWithChildren
  '/portfolio': typeof PortfolioRoute
  '/sobre': typeof SobreRoute
  '/transmissoras': typeof TransmissorasRoute
  '/investidores/demonstracoes-financeiras': typeof InvestidoresDemonstracoesFinanceirasRoute
  '/investidores/outros-documentos': typeof InvestidoresOutrosDocumentosRoute
  '/investidores/relatorios-agente-fiduciario': typeof InvestidoresRelatoriosAgenteFiduciarioRoute
  '/investidores/transmissora-spmg-s-a': typeof InvestidoresTransmissoraSpmgSARoute
  '/investidores/': typeof InvestidoresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/empresas'
    | '/eolicas'
    | '/esg'
    | '/etica'
    | '/investidores'
    | '/portfolio'
    | '/sobre'
    | '/transmissoras'
    | '/investidores/demonstracoes-financeiras'
    | '/investidores/outros-documentos'
    | '/investidores/relatorios-agente-fiduciario'
    | '/investidores/transmissora-spmg-s-a'
    | '/investidores/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/empresas'
    | '/eolicas'
    | '/esg'
    | '/etica'
    | '/portfolio'
    | '/sobre'
    | '/transmissoras'
    | '/investidores/demonstracoes-financeiras'
    | '/investidores/outros-documentos'
    | '/investidores/relatorios-agente-fiduciario'
    | '/investidores/transmissora-spmg-s-a'
    | '/investidores'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/empresas'
    | '/eolicas'
    | '/esg'
    | '/etica'
    | '/investidores'
    | '/portfolio'
    | '/sobre'
    | '/transmissoras'
    | '/investidores/demonstracoes-financeiras'
    | '/investidores/outros-documentos'
    | '/investidores/relatorios-agente-fiduciario'
    | '/investidores/transmissora-spmg-s-a'
    | '/investidores/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  EmpresasRoute: typeof EmpresasRoute
  EolicasRoute: typeof EolicasRoute
  EsgRoute: typeof EsgRoute
  EticaRoute: typeof EticaRoute
  InvestidoresRoute: typeof InvestidoresRouteWithChildren
  PortfolioRoute: typeof PortfolioRoute
  SobreRoute: typeof SobreRoute
  TransmissorasRoute: typeof TransmissorasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transmissoras': {
      id: '/transmissoras'
      path: '/transmissoras'
      fullPath: '/transmissoras'
      preLoaderRoute: typeof TransmissorasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investidores': {
      id: '/investidores'
      path: '/investidores'
      fullPath: '/investidores'
      preLoaderRoute: typeof InvestidoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etica': {
      id: '/etica'
      path: '/etica'
      fullPath: '/etica'
      preLoaderRoute: typeof EticaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esg': {
      id: '/esg'
      path: '/esg'
      fullPath: '/esg'
      preLoaderRoute: typeof EsgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eolicas': {
      id: '/eolicas'
      path: '/eolicas'
      fullPath: '/eolicas'
      preLoaderRoute: typeof EolicasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas': {
      id: '/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof EmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investidores/': {
      id: '/investidores/'
      path: '/'
      fullPath: '/investidores/'
      preLoaderRoute: typeof InvestidoresIndexRouteImport
      parentRoute: typeof InvestidoresRoute
    }
    '/investidores/transmissora-spmg-s-a': {
      id: '/investidores/transmissora-spmg-s-a'
      path: '/transmissora-spmg-s-a'
      fullPath: '/investidores/transmissora-spmg-s-a'
      preLoaderRoute: typeof InvestidoresTransmissoraSpmgSARouteImport
      parentRoute: typeof InvestidoresRoute
    }
    '/investidores/relatorios-agente-fiduciario': {
      id: '/investidores/relatorios-agente-fiduciario'
      path: '/relatorios-agente-fiduciario'
      fullPath: '/investidores/relatorios-agente-fiduciario'
      preLoaderRoute: typeof InvestidoresRelatoriosAgenteFiduciarioRouteImport
      parentRoute: typeof InvestidoresRoute
    }
    '/investidores/outros-documentos': {
      id: '/investidores/outros-documentos'
      path: '/outros-documentos'
      fullPath: '/investidores/outros-documentos'
      preLoaderRoute: typeof InvestidoresOutrosDocumentosRouteImport
      parentRoute: typeof InvestidoresRoute
    }
    '/investidores/demonstracoes-financeiras': {
      id: '/investidores/demonstracoes-financeiras'
      path: '/demonstracoes-financeiras'
      fullPath: '/investidores/demonstracoes-financeiras'
      preLoaderRoute: typeof InvestidoresDemonstracoesFinanceirasRouteImport
      parentRoute: typeof InvestidoresRoute
    }
  }
}

interface InvestidoresRouteChildren {
  InvestidoresDemonstracoesFinanceirasRoute: typeof InvestidoresDemonstracoesFinanceirasRoute
  InvestidoresOutrosDocumentosRoute: typeof InvestidoresOutrosDocumentosRoute
  InvestidoresRelatoriosAgenteFiduciarioRoute: typeof InvestidoresRelatoriosAgenteFiduciarioRoute
  InvestidoresTransmissoraSpmgSARoute: typeof InvestidoresTransmissoraSpmgSARoute
  InvestidoresIndexRoute: typeof InvestidoresIndexRoute
}

const InvestidoresRouteChildren: InvestidoresRouteChildren = {
  InvestidoresDemonstracoesFinanceirasRoute:
    InvestidoresDemonstracoesFinanceirasRoute,
  InvestidoresOutrosDocumentosRoute: InvestidoresOutrosDocumentosRoute,
  InvestidoresRelatoriosAgenteFiduciarioRoute:
    InvestidoresRelatoriosAgenteFiduciarioRoute,
  InvestidoresTransmissoraSpmgSARoute: InvestidoresTransmissoraSpmgSARoute,
  InvestidoresIndexRoute: InvestidoresIndexRoute,
}

const InvestidoresRouteWithChildren = InvestidoresRoute._addFileChildren(
  InvestidoresRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  EmpresasRoute: EmpresasRoute,
  EolicasRoute: EolicasRoute,
  EsgRoute: EsgRoute,
  EticaRoute: EticaRoute,
  InvestidoresRoute: InvestidoresRouteWithChildren,
  PortfolioRoute: PortfolioRoute,
  SobreRoute: SobreRoute,
  TransmissorasRoute: TransmissorasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
