/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransmissorasRouteImport } from './routes/transmissoras'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as InvestidoresRouteImport } from './routes/investidores'
import { Route as EsgRouteImport } from './routes/esg'
import { Route as EolicasRouteImport } from './routes/eolicas'
import { Route as EmpresasRouteImport } from './routes/empresas'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as IndexRouteImport } from './routes/index'

const TransmissorasRoute = TransmissorasRouteImport.update({
  id: '/transmissoras',
  path: '/transmissoras',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestidoresRoute = InvestidoresRouteImport.update({
  id: '/investidores',
  path: '/investidores',
  getParentRoute: () => rootRouteImport,
} as any)
const EsgRoute = EsgRouteImport.update({
  id: '/esg',
  path: '/esg',
  getParentRoute: () => rootRouteImport,
} as any)
const EolicasRoute = EolicasRouteImport.update({
  id: '/eolicas',
  path: '/eolicas',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasRoute = EmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/empresas': typeof EmpresasRoute
  '/eolicas': typeof EolicasRoute
  '/esg': typeof EsgRoute
  '/investidores': typeof InvestidoresRoute
  '/portfolio': typeof PortfolioRoute
  '/sobre': typeof SobreRoute
  '/transmissoras': typeof TransmissorasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/empresas': typeof EmpresasRoute
  '/eolicas': typeof EolicasRoute
  '/esg': typeof EsgRoute
  '/investidores': typeof InvestidoresRoute
  '/portfolio': typeof PortfolioRoute
  '/sobre': typeof SobreRoute
  '/transmissoras': typeof TransmissorasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/empresas': typeof EmpresasRoute
  '/eolicas': typeof EolicasRoute
  '/esg': typeof EsgRoute
  '/investidores': typeof InvestidoresRoute
  '/portfolio': typeof PortfolioRoute
  '/sobre': typeof SobreRoute
  '/transmissoras': typeof TransmissorasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/empresas'
    | '/eolicas'
    | '/esg'
    | '/investidores'
    | '/portfolio'
    | '/sobre'
    | '/transmissoras'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/empresas'
    | '/eolicas'
    | '/esg'
    | '/investidores'
    | '/portfolio'
    | '/sobre'
    | '/transmissoras'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/empresas'
    | '/eolicas'
    | '/esg'
    | '/investidores'
    | '/portfolio'
    | '/sobre'
    | '/transmissoras'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  EmpresasRoute: typeof EmpresasRoute
  EolicasRoute: typeof EolicasRoute
  EsgRoute: typeof EsgRoute
  InvestidoresRoute: typeof InvestidoresRoute
  PortfolioRoute: typeof PortfolioRoute
  SobreRoute: typeof SobreRoute
  TransmissorasRoute: typeof TransmissorasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transmissoras': {
      id: '/transmissoras'
      path: '/transmissoras'
      fullPath: '/transmissoras'
      preLoaderRoute: typeof TransmissorasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investidores': {
      id: '/investidores'
      path: '/investidores'
      fullPath: '/investidores'
      preLoaderRoute: typeof InvestidoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esg': {
      id: '/esg'
      path: '/esg'
      fullPath: '/esg'
      preLoaderRoute: typeof EsgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eolicas': {
      id: '/eolicas'
      path: '/eolicas'
      fullPath: '/eolicas'
      preLoaderRoute: typeof EolicasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas': {
      id: '/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof EmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  EmpresasRoute: EmpresasRoute,
  EolicasRoute: EolicasRoute,
  EsgRoute: EsgRoute,
  InvestidoresRoute: InvestidoresRoute,
  PortfolioRoute: PortfolioRoute,
  SobreRoute: SobreRoute,
  TransmissorasRoute: TransmissorasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
