/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as EolicasRouteImport } from './routes/eolicas'
import { Route as EsgRouteImport } from './routes/esg'
import { Route as EticaRouteImport } from './routes/etica'
import { Route as InvestidoresRouteImport } from './routes/investidores'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as TransmissorasRouteImport } from './routes/transmissoras'
import { Route as EticaIndexRouteImport } from './routes/etica/index'
import { Route as EticaAcompanharRelatoRouteImport } from './routes/etica/acompanhar-relato'
import { Route as EticaCanalDeDenunciasRouteImport } from './routes/etica/canal-de-denuncias'
import { Route as EticaDadosIncidenteRouteImport } from './routes/etica/dados-incidente'
import { Route as EticaDetalhesRelatoRouteImport } from './routes/etica/detalhes-relato'
import { Route as EticaIdentificacaoRelatoRouteImport } from './routes/etica/identificacao-relato'
import { Route as EticaPoliticaAnticorrupcaoRouteImport } from './routes/etica/politica-anticorrupcao'
import { Route as EticaProtecaoDadosRouteImport } from './routes/etica/protecao-dados'
import { Route as EticaRealizarRelatoRouteImport } from './routes/etica/realizar-relato'
import { Route as EticaRelatoSucessoRouteImport } from './routes/etica/relato-sucesso'
import { Route as EticaRelatoriosSustentabilidadeRouteImport } from './routes/etica/relatorios-sustentabilidade'
import { Route as InvestidoresIndexRouteImport } from './routes/investidores/index'
import { Route as InvestidoresDemonstracoesFinanceirasRouteImport } from './routes/investidores/demonstracoes-financeiras'
import { Route as InvestidoresOutrosDocumentosRouteImport } from './routes/investidores/outros-documentos'
import { Route as InvestidoresRelatoriosAgenteFiduciarioRouteImport } from './routes/investidores/relatorios-agente-fiduciario'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/contato.lazy').then((d) => d.Route))
const EolicasRoute = EolicasRouteImport.update({
  id: '/eolicas',
  path: '/eolicas',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/eolicas.lazy').then((d) => d.Route))
const EsgRoute = EsgRouteImport.update({
  id: '/esg',
  path: '/esg',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/esg.lazy').then((d) => d.Route))
const EticaRoute = EticaRouteImport.update({
  id: '/etica',
  path: '/etica',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestidoresRoute = InvestidoresRouteImport.update({
  id: '/investidores',
  path: '/investidores',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/portfolio.lazy').then((d) => d.Route))
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/sobre.lazy').then((d) => d.Route))
const TransmissorasRoute = TransmissorasRouteImport.update({
  id: '/transmissoras',
  path: '/transmissoras',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/transmissoras.lazy').then((d) => d.Route))
const EticaIndexRoute = EticaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EticaRoute,
} as any).lazy(() => import('./routes/etica/index.lazy').then((d) => d.Route))
const EticaAcompanharRelatoRoute = EticaAcompanharRelatoRouteImport.update({
  id: '/acompanhar-relato',
  path: '/acompanhar-relato',
  getParentRoute: () => EticaRoute,
} as any)
const EticaCanalDeDenunciasRoute = EticaCanalDeDenunciasRouteImport.update({
  id: '/canal-de-denuncias',
  path: '/canal-de-denuncias',
  getParentRoute: () => EticaRoute,
} as any)
const EticaDadosIncidenteRoute = EticaDadosIncidenteRouteImport.update({
  id: '/dados-incidente',
  path: '/dados-incidente',
  getParentRoute: () => EticaRoute,
} as any)
const EticaDetalhesRelatoRoute = EticaDetalhesRelatoRouteImport.update({
  id: '/detalhes-relato',
  path: '/detalhes-relato',
  getParentRoute: () => EticaRoute,
} as any)
const EticaIdentificacaoRelatoRoute =
  EticaIdentificacaoRelatoRouteImport.update({
    id: '/identificacao-relato',
    path: '/identificacao-relato',
    getParentRoute: () => EticaRoute,
  } as any)
const EticaPoliticaAnticorrupcaoRoute =
  EticaPoliticaAnticorrupcaoRouteImport.update({
    id: '/politica-anticorrupcao',
    path: '/politica-anticorrupcao',
    getParentRoute: () => EticaRoute,
  } as any)
const EticaProtecaoDadosRoute = EticaProtecaoDadosRouteImport.update({
  id: '/protecao-dados',
  path: '/protecao-dados',
  getParentRoute: () => EticaRoute,
} as any)
const EticaRealizarRelatoRoute = EticaRealizarRelatoRouteImport.update({
  id: '/realizar-relato',
  path: '/realizar-relato',
  getParentRoute: () => EticaRoute,
} as any)
const EticaRelatoSucessoRoute = EticaRelatoSucessoRouteImport.update({
  id: '/relato-sucesso',
  path: '/relato-sucesso',
  getParentRoute: () => EticaRoute,
} as any)
const EticaRelatoriosSustentabilidadeRoute =
  EticaRelatoriosSustentabilidadeRouteImport.update({
    id: '/relatorios-sustentabilidade',
    path: '/relatorios-sustentabilidade',
    getParentRoute: () => EticaRoute,
  } as any)
const InvestidoresIndexRoute = InvestidoresIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InvestidoresRoute,
} as any).lazy(() =>
  import('./routes/investidores/index.lazy').then((d) => d.Route),
)
const InvestidoresDemonstracoesFinanceirasRoute =
  InvestidoresDemonstracoesFinanceirasRouteImport.update({
    id: '/demonstracoes-financeiras',
    path: '/demonstracoes-financeiras',
    getParentRoute: () => InvestidoresRoute,
  } as any)
const InvestidoresOutrosDocumentosRoute =
  InvestidoresOutrosDocumentosRouteImport.update({
    id: '/outros-documentos',
    path: '/outros-documentos',
    getParentRoute: () => InvestidoresRoute,
  } as any)
const InvestidoresRelatoriosAgenteFiduciarioRoute =
  InvestidoresRelatoriosAgenteFiduciarioRouteImport.update({
    id: '/relatorios-agente-fiduciario',
    path: '/relatorios-agente-fiduciario',
    getParentRoute: () => InvestidoresRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/eolicas': typeof EolicasRoute
  '/esg': typeof EsgRoute
  '/etica': typeof EticaRouteWithChildren
  '/investidores': typeof InvestidoresRouteWithChildren
  '/portfolio': typeof PortfolioRoute
  '/sobre': typeof SobreRoute
  '/transmissoras': typeof TransmissorasRoute
  '/etica/acompanhar-relato': typeof EticaAcompanharRelatoRoute
  '/etica/canal-de-denuncias': typeof EticaCanalDeDenunciasRoute
  '/etica/dados-incidente': typeof EticaDadosIncidenteRoute
  '/etica/detalhes-relato': typeof EticaDetalhesRelatoRoute
  '/etica/identificacao-relato': typeof EticaIdentificacaoRelatoRoute
  '/etica/politica-anticorrupcao': typeof EticaPoliticaAnticorrupcaoRoute
  '/etica/protecao-dados': typeof EticaProtecaoDadosRoute
  '/etica/realizar-relato': typeof EticaRealizarRelatoRoute
  '/etica/relato-sucesso': typeof EticaRelatoSucessoRoute
  '/etica/relatorios-sustentabilidade': typeof EticaRelatoriosSustentabilidadeRoute
  '/investidores/demonstracoes-financeiras': typeof InvestidoresDemonstracoesFinanceirasRoute
  '/investidores/outros-documentos': typeof InvestidoresOutrosDocumentosRoute
  '/investidores/relatorios-agente-fiduciario': typeof InvestidoresRelatoriosAgenteFiduciarioRoute
  '/etica/': typeof EticaIndexRoute
  '/investidores/': typeof InvestidoresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/eolicas': typeof EolicasRoute
  '/esg': typeof EsgRoute
  '/portfolio': typeof PortfolioRoute
  '/sobre': typeof SobreRoute
  '/transmissoras': typeof TransmissorasRoute
  '/etica/acompanhar-relato': typeof EticaAcompanharRelatoRoute
  '/etica/canal-de-denuncias': typeof EticaCanalDeDenunciasRoute
  '/etica/dados-incidente': typeof EticaDadosIncidenteRoute
  '/etica/detalhes-relato': typeof EticaDetalhesRelatoRoute
  '/etica/identificacao-relato': typeof EticaIdentificacaoRelatoRoute
  '/etica/politica-anticorrupcao': typeof EticaPoliticaAnticorrupcaoRoute
  '/etica/protecao-dados': typeof EticaProtecaoDadosRoute
  '/etica/realizar-relato': typeof EticaRealizarRelatoRoute
  '/etica/relato-sucesso': typeof EticaRelatoSucessoRoute
  '/etica/relatorios-sustentabilidade': typeof EticaRelatoriosSustentabilidadeRoute
  '/investidores/demonstracoes-financeiras': typeof InvestidoresDemonstracoesFinanceirasRoute
  '/investidores/outros-documentos': typeof InvestidoresOutrosDocumentosRoute
  '/investidores/relatorios-agente-fiduciario': typeof InvestidoresRelatoriosAgenteFiduciarioRoute
  '/etica': typeof EticaIndexRoute
  '/investidores': typeof InvestidoresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/eolicas': typeof EolicasRoute
  '/esg': typeof EsgRoute
  '/etica': typeof EticaRouteWithChildren
  '/investidores': typeof InvestidoresRouteWithChildren
  '/portfolio': typeof PortfolioRoute
  '/sobre': typeof SobreRoute
  '/transmissoras': typeof TransmissorasRoute
  '/etica/acompanhar-relato': typeof EticaAcompanharRelatoRoute
  '/etica/canal-de-denuncias': typeof EticaCanalDeDenunciasRoute
  '/etica/dados-incidente': typeof EticaDadosIncidenteRoute
  '/etica/detalhes-relato': typeof EticaDetalhesRelatoRoute
  '/etica/identificacao-relato': typeof EticaIdentificacaoRelatoRoute
  '/etica/politica-anticorrupcao': typeof EticaPoliticaAnticorrupcaoRoute
  '/etica/protecao-dados': typeof EticaProtecaoDadosRoute
  '/etica/realizar-relato': typeof EticaRealizarRelatoRoute
  '/etica/relato-sucesso': typeof EticaRelatoSucessoRoute
  '/etica/relatorios-sustentabilidade': typeof EticaRelatoriosSustentabilidadeRoute
  '/investidores/demonstracoes-financeiras': typeof InvestidoresDemonstracoesFinanceirasRoute
  '/investidores/outros-documentos': typeof InvestidoresOutrosDocumentosRoute
  '/investidores/relatorios-agente-fiduciario': typeof InvestidoresRelatoriosAgenteFiduciarioRoute
  '/etica/': typeof EticaIndexRoute
  '/investidores/': typeof InvestidoresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/eolicas'
    | '/esg'
    | '/etica'
    | '/investidores'
    | '/portfolio'
    | '/sobre'
    | '/transmissoras'
    | '/etica/acompanhar-relato'
    | '/etica/canal-de-denuncias'
    | '/etica/dados-incidente'
    | '/etica/detalhes-relato'
    | '/etica/identificacao-relato'
    | '/etica/politica-anticorrupcao'
    | '/etica/protecao-dados'
    | '/etica/realizar-relato'
    | '/etica/relato-sucesso'
    | '/etica/relatorios-sustentabilidade'
    | '/investidores/demonstracoes-financeiras'
    | '/investidores/outros-documentos'
    | '/investidores/relatorios-agente-fiduciario'
    | '/etica/'
    | '/investidores/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/eolicas'
    | '/esg'
    | '/portfolio'
    | '/sobre'
    | '/transmissoras'
    | '/etica/acompanhar-relato'
    | '/etica/canal-de-denuncias'
    | '/etica/dados-incidente'
    | '/etica/detalhes-relato'
    | '/etica/identificacao-relato'
    | '/etica/politica-anticorrupcao'
    | '/etica/protecao-dados'
    | '/etica/realizar-relato'
    | '/etica/relato-sucesso'
    | '/etica/relatorios-sustentabilidade'
    | '/investidores/demonstracoes-financeiras'
    | '/investidores/outros-documentos'
    | '/investidores/relatorios-agente-fiduciario'
    | '/etica'
    | '/investidores'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/eolicas'
    | '/esg'
    | '/etica'
    | '/investidores'
    | '/portfolio'
    | '/sobre'
    | '/transmissoras'
    | '/etica/acompanhar-relato'
    | '/etica/canal-de-denuncias'
    | '/etica/dados-incidente'
    | '/etica/detalhes-relato'
    | '/etica/identificacao-relato'
    | '/etica/politica-anticorrupcao'
    | '/etica/protecao-dados'
    | '/etica/realizar-relato'
    | '/etica/relato-sucesso'
    | '/etica/relatorios-sustentabilidade'
    | '/investidores/demonstracoes-financeiras'
    | '/investidores/outros-documentos'
    | '/investidores/relatorios-agente-fiduciario'
    | '/etica/'
    | '/investidores/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  EolicasRoute: typeof EolicasRoute
  EsgRoute: typeof EsgRoute
  EticaRoute: typeof EticaRouteWithChildren
  InvestidoresRoute: typeof InvestidoresRouteWithChildren
  PortfolioRoute: typeof PortfolioRoute
  SobreRoute: typeof SobreRoute
  TransmissorasRoute: typeof TransmissorasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eolicas': {
      id: '/eolicas'
      path: '/eolicas'
      fullPath: '/eolicas'
      preLoaderRoute: typeof EolicasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esg': {
      id: '/esg'
      path: '/esg'
      fullPath: '/esg'
      preLoaderRoute: typeof EsgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etica': {
      id: '/etica'
      path: '/etica'
      fullPath: '/etica'
      preLoaderRoute: typeof EticaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investidores': {
      id: '/investidores'
      path: '/investidores'
      fullPath: '/investidores'
      preLoaderRoute: typeof InvestidoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transmissoras': {
      id: '/transmissoras'
      path: '/transmissoras'
      fullPath: '/transmissoras'
      preLoaderRoute: typeof TransmissorasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etica/': {
      id: '/etica/'
      path: '/'
      fullPath: '/etica/'
      preLoaderRoute: typeof EticaIndexRouteImport
      parentRoute: typeof EticaRoute
    }
    '/etica/acompanhar-relato': {
      id: '/etica/acompanhar-relato'
      path: '/acompanhar-relato'
      fullPath: '/etica/acompanhar-relato'
      preLoaderRoute: typeof EticaAcompanharRelatoRouteImport
      parentRoute: typeof EticaRoute
    }
    '/etica/canal-de-denuncias': {
      id: '/etica/canal-de-denuncias'
      path: '/canal-de-denuncias'
      fullPath: '/etica/canal-de-denuncias'
      preLoaderRoute: typeof EticaCanalDeDenunciasRouteImport
      parentRoute: typeof EticaRoute
    }
    '/etica/dados-incidente': {
      id: '/etica/dados-incidente'
      path: '/dados-incidente'
      fullPath: '/etica/dados-incidente'
      preLoaderRoute: typeof EticaDadosIncidenteRouteImport
      parentRoute: typeof EticaRoute
    }
    '/etica/detalhes-relato': {
      id: '/etica/detalhes-relato'
      path: '/detalhes-relato'
      fullPath: '/etica/detalhes-relato'
      preLoaderRoute: typeof EticaDetalhesRelatoRouteImport
      parentRoute: typeof EticaRoute
    }
    '/etica/identificacao-relato': {
      id: '/etica/identificacao-relato'
      path: '/identificacao-relato'
      fullPath: '/etica/identificacao-relato'
      preLoaderRoute: typeof EticaIdentificacaoRelatoRouteImport
      parentRoute: typeof EticaRoute
    }
    '/etica/politica-anticorrupcao': {
      id: '/etica/politica-anticorrupcao'
      path: '/politica-anticorrupcao'
      fullPath: '/etica/politica-anticorrupcao'
      preLoaderRoute: typeof EticaPoliticaAnticorrupcaoRouteImport
      parentRoute: typeof EticaRoute
    }
    '/etica/protecao-dados': {
      id: '/etica/protecao-dados'
      path: '/protecao-dados'
      fullPath: '/etica/protecao-dados'
      preLoaderRoute: typeof EticaProtecaoDadosRouteImport
      parentRoute: typeof EticaRoute
    }
    '/etica/realizar-relato': {
      id: '/etica/realizar-relato'
      path: '/realizar-relato'
      fullPath: '/etica/realizar-relato'
      preLoaderRoute: typeof EticaRealizarRelatoRouteImport
      parentRoute: typeof EticaRoute
    }
    '/etica/relato-sucesso': {
      id: '/etica/relato-sucesso'
      path: '/relato-sucesso'
      fullPath: '/etica/relato-sucesso'
      preLoaderRoute: typeof EticaRelatoSucessoRouteImport
      parentRoute: typeof EticaRoute
    }
    '/etica/relatorios-sustentabilidade': {
      id: '/etica/relatorios-sustentabilidade'
      path: '/relatorios-sustentabilidade'
      fullPath: '/etica/relatorios-sustentabilidade'
      preLoaderRoute: typeof EticaRelatoriosSustentabilidadeRouteImport
      parentRoute: typeof EticaRoute
    }
    '/investidores/': {
      id: '/investidores/'
      path: '/'
      fullPath: '/investidores/'
      preLoaderRoute: typeof InvestidoresIndexRouteImport
      parentRoute: typeof InvestidoresRoute
    }
    '/investidores/demonstracoes-financeiras': {
      id: '/investidores/demonstracoes-financeiras'
      path: '/demonstracoes-financeiras'
      fullPath: '/investidores/demonstracoes-financeiras'
      preLoaderRoute: typeof InvestidoresDemonstracoesFinanceirasRouteImport
      parentRoute: typeof InvestidoresRoute
    }
    '/investidores/outros-documentos': {
      id: '/investidores/outros-documentos'
      path: '/outros-documentos'
      fullPath: '/investidores/outros-documentos'
      preLoaderRoute: typeof InvestidoresOutrosDocumentosRouteImport
      parentRoute: typeof InvestidoresRoute
    }
    '/investidores/relatorios-agente-fiduciario': {
      id: '/investidores/relatorios-agente-fiduciario'
      path: '/relatorios-agente-fiduciario'
      fullPath: '/investidores/relatorios-agente-fiduciario'
      preLoaderRoute: typeof InvestidoresRelatoriosAgenteFiduciarioRouteImport
      parentRoute: typeof InvestidoresRoute
    }
  }
}

interface EticaRouteChildren {
  EticaAcompanharRelatoRoute: typeof EticaAcompanharRelatoRoute
  EticaCanalDeDenunciasRoute: typeof EticaCanalDeDenunciasRoute
  EticaDadosIncidenteRoute: typeof EticaDadosIncidenteRoute
  EticaDetalhesRelatoRoute: typeof EticaDetalhesRelatoRoute
  EticaIdentificacaoRelatoRoute: typeof EticaIdentificacaoRelatoRoute
  EticaPoliticaAnticorrupcaoRoute: typeof EticaPoliticaAnticorrupcaoRoute
  EticaProtecaoDadosRoute: typeof EticaProtecaoDadosRoute
  EticaRealizarRelatoRoute: typeof EticaRealizarRelatoRoute
  EticaRelatoSucessoRoute: typeof EticaRelatoSucessoRoute
  EticaRelatoriosSustentabilidadeRoute: typeof EticaRelatoriosSustentabilidadeRoute
  EticaIndexRoute: typeof EticaIndexRoute
}

const EticaRouteChildren: EticaRouteChildren = {
  EticaAcompanharRelatoRoute: EticaAcompanharRelatoRoute,
  EticaCanalDeDenunciasRoute: EticaCanalDeDenunciasRoute,
  EticaDadosIncidenteRoute: EticaDadosIncidenteRoute,
  EticaDetalhesRelatoRoute: EticaDetalhesRelatoRoute,
  EticaIdentificacaoRelatoRoute: EticaIdentificacaoRelatoRoute,
  EticaPoliticaAnticorrupcaoRoute: EticaPoliticaAnticorrupcaoRoute,
  EticaProtecaoDadosRoute: EticaProtecaoDadosRoute,
  EticaRealizarRelatoRoute: EticaRealizarRelatoRoute,
  EticaRelatoSucessoRoute: EticaRelatoSucessoRoute,
  EticaRelatoriosSustentabilidadeRoute: EticaRelatoriosSustentabilidadeRoute,
  EticaIndexRoute: EticaIndexRoute,
}

const EticaRouteWithChildren = EticaRoute._addFileChildren(EticaRouteChildren)

interface InvestidoresRouteChildren {
  InvestidoresDemonstracoesFinanceirasRoute: typeof InvestidoresDemonstracoesFinanceirasRoute
  InvestidoresOutrosDocumentosRoute: typeof InvestidoresOutrosDocumentosRoute
  InvestidoresRelatoriosAgenteFiduciarioRoute: typeof InvestidoresRelatoriosAgenteFiduciarioRoute
  InvestidoresIndexRoute: typeof InvestidoresIndexRoute
}

const InvestidoresRouteChildren: InvestidoresRouteChildren = {
  InvestidoresDemonstracoesFinanceirasRoute:
    InvestidoresDemonstracoesFinanceirasRoute,
  InvestidoresOutrosDocumentosRoute: InvestidoresOutrosDocumentosRoute,
  InvestidoresRelatoriosAgenteFiduciarioRoute:
    InvestidoresRelatoriosAgenteFiduciarioRoute,
  InvestidoresIndexRoute: InvestidoresIndexRoute,
}

const InvestidoresRouteWithChildren = InvestidoresRoute._addFileChildren(
  InvestidoresRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  EolicasRoute: EolicasRoute,
  EsgRoute: EsgRoute,
  EticaRoute: EticaRouteWithChildren,
  InvestidoresRoute: InvestidoresRouteWithChildren,
  PortfolioRoute: PortfolioRoute,
  SobreRoute: SobreRoute,
  TransmissorasRoute: TransmissorasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
